version: "3.8"

services:
  backend:
    build: .
    container_name: bot-backend
    restart: always
    ports:
      - "8080:8080"

  n8n-db:
    image: postgres:14
    container_name: n8n-db
    restart: always
    environment:
      POSTGRES_DB: n8ndb
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8npass
    volumes:
      - n8n_postgres_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n:2.2.4
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: n8n-db
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8ndb
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8npass

      N8N_HOST: localhost
      N8N_PORT: 5678
      N8N_PROTOCOL: http

      TZ: Asia/Bangkok
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - n8n-db

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: always
    command: http backend:8080
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    depends_on:
      - backend

volumes:
  n8n_postgres_data:
  n8n_data: