spring.application.name=pccth-km-bot-backend

n8n.webhook.url=http://n8n:5678/webhook/line-receive
line.set.webhook=https://api.line.me/v2/bot/channel/webhook/endpoint
line.test.webhook=https://api.line.me/v2/bot/channel/webhook/test